services:
  bot:
    # image: ghcr.io/fitztrev/zulip-lichess:docker
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_DB=5
      - HOSTED_ON=
      - REPO_URL=https://github.com/fitztrev/zulip-lichess
    volumes:
      - ./zuliprc:/app/zuliprc:ro

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1

volumes:
  redis_data:
