services:
  bot:
    image: ghcr.io/fitztrev/zulip-lichess:docker
    environment:
      - REDIS_HOST=redis
      - REDIS_DB=0
    volumes:
      - ./zuliprc:/app/zuliprc:ro

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1

volumes:
  redis_data:
